function createplot(Y1)
%CREATEPLOT(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 20-Mar-2014 11:45:38

% Create plot
plot(Y1,'Marker','.','LineWidth',2,'LineStyle','none','Color',[0 0 0]);

